/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.listCtl;
import controller.loginCtl;
import controller.searchCtl;
import controller.topicCtl;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;

/**
 *
 * @author Admin
 */
public class SearchFrm extends javax.swing.JFrame {

    /**
     * Creates new form SearchFrm
     */
    
    searchCtl search = new searchCtl();
    topicCtl tp = new topicCtl(); 
    listCtl listCtl = new listCtl();
    String result;
    public SearchFrm() {
        initComponents();
        this.setSize(1215, 730); // Kích cỡ Frame
        this.setTitle("Search");// Tiêu đề
        this.setVisible(true);// Hiển thị
        this.setLocationRelativeTo(null);// Chính giữa màn hình
        txtEn.setText("ENGLISH");
        txtVn.setText("VIETNAMESE");
        btnRemember.setVisible(false);
        star1.setVisible(false);
        star2.setVisible(false);
        setBtn();// Xóa viền button
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRemember = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JToggleButton();
        txtEn = new javax.swing.JTextField();
        txtVn = new javax.swing.JTextField();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        JbableOne = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnRemember.setBackground(new java.awt.Color(255, 255, 255));
        btnRemember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRememberMouseClicked(evt);
            }
        });
        btnRemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRememberActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemember);
        btnRemember.setBounds(1050, 210, 70, 80);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(10, 20, 100, 100);

        txtEn.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtEn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEnMouseClicked(evt);
            }
        });
        txtEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnActionPerformed(evt);
            }
        });
        txtEn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEnKeyPressed(evt);
            }
        });
        getContentPane().add(txtEn);
        txtEn.setBounds(420, 330, 700, 110);

        txtVn.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(txtVn);
        txtVn.setBounds(420, 500, 700, 110);

        star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/yellowStar.png"))); // NOI18N
        getContentPane().add(star1);
        star1.setBounds(1050, 220, 70, 70);

        star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blackStar.png"))); // NOI18N
        getContentPane().add(star2);
        star2.setBounds(1050, 220, 70, 70);

        JbableOne.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JbableOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DICTIONARY_1.png"))); // NOI18N
        JbableOne.setText("ENTERTREXXT");
        getContentPane().add(JbableOne);
        JbableOne.setBounds(0, 0, 1210, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    


    public void setBtnNoBorder(JToggleButton button) {//Xóa viền button
        button.setOpaque(false);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0)); // Especially important
    }

    public void setBtn() {// Xóa viền button Back và button Remeber
        setBtnNoBorder(btnBack);
        setBtnNoBorder(btnRemember);
    }

    public boolean checkBlack()// Kiểm tra Jtext nhập từ tiếng anh có trống không?
    {
        return txtEn.getText().trim().equals("");
    }
    
    public void announcement(String str) // Hiện thị thông báo
    {
        JOptionPane.showMessageDialog(null, str);
    }
    
    
    public void setStar()//Hiện thị Star
    {
        if(search.checkWordExits(topicCtl.idperson, txtEn.getText()))
        {
            this.star1.setVisible(true); 
            this.star2.setVisible(false);
        }
        else
        {
            this.star1.setVisible(false);
            this.star2.setVisible(true);
        }
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new HomeFrm();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRememberActionPerformed
        if(search.checkWordExits(topicCtl.idperson, txtEn.getText()))// Kiem tra tu vung ton tai chua
        {
            listCtl.removeWord(txtEn.getText()); // Neu ton tai thi xoa khoi ds tu vung cua user
        }
        else
        {
            tp.addWordToPersonList(topicCtl.idperson, tp.getIDword(txtEn.getText()));// Chua ton tai thi add vào danh sách từ vựng của bản thân
        }
        setStar(); // Hiển thị Star
        
    }//GEN-LAST:event_btnRememberActionPerformed

    private void btnRememberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRememberMouseClicked
        
    }//GEN-LAST:event_btnRememberMouseClicked

    private void txtEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnActionPerformed

    }//GEN-LAST:event_txtEnActionPerformed

    private void txtEnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEnMouseClicked
        txtEn.setText("");// Bắt sự kiện ấn chuột vào mục tìm kiếm từ vựng bằng tiếng anh
        txtVn.setText("");
        btnRemember.setVisible(false);
        star1.setVisible(false);
        star2.setVisible(false);
    }//GEN-LAST:event_txtEnMouseClicked

    private void txtEnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)// Bắt sự kiện ấn phím enter
        {
                if(!checkBlack())// Nếu các trường đều khác rỗng
                { 
                    result = search.wordResult(txtEn.getText());// Kết quả của từ vựng tìm kiếm tiếng anh
                    if(result == null)
                    {
                        announcement("No result");
                        txtEn.setText("");
                    }
                    else
                    {
                        txtVn.setText(result);
                        setStar();
                        btnRemember.setVisible(true);
                    }
                }
        }
    }//GEN-LAST:event_txtEnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JbableOne;
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnRemember;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JTextField txtEn;
    private javax.swing.JTextField txtVn;
    // End of variables declaration//GEN-END:variables
}
