/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.listCtl;
import controller.loginCtl;
import controller.searchCtl;
import controller.topicCtl;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import model.word;

/**
 *
 * @author Admin
 */
public class TopicFrm extends javax.swing.JFrame {

    /**
     * Creates new form TopicFrm
     */
    topicCtl tp = new topicCtl();
    DefaultTableModel model;
    ArrayList<word> topicList; //Word list by topic
    ArrayList<String> topicnameList; // topicnameList to setItem topicCombobox

    public TopicFrm() {
        initComponents();
        this.setSize(1210, 720);// Kích thước
        this.setVisible(true);// Hiện thị Jframe
        this.setTitle("Topic"); // Tiêu đề
        this.setLocationRelativeTo(null);// Hiển thị ở chính giữa màn hình
        setBtn(); // Xóa viền các button 

        model = (DefaultTableModel) topicTable.getModel();
//        model.setColumnIdentifiers(new Object[]{
//            "English", "Vietnamese"
//        });
        showdatacombo();
    }

    private void showdatacombo() { //Tạo danh sách chủ đề ở comboBox chủ đề
        for (String str : tp.getTopicName()) {
            topicBox.addItem(str);
        }
    }

    private void announcement(String str) { // Thông báo
        JOptionPane.showMessageDialog(null, str);
    }

    private void showTable(String topicName) {//Hiển thị danh sách từ vựng theo chủ đề
        topicList = tp.getTopic(topicName);
        for (word x : topicList) {
            model.addRow(new Object[]{
                x.getEn(), x.getVn()
            });
        }
    }
    public void setBtnNoBorder(JToggleButton button) // Xóa viền button
    {
        button.setOpaque(false);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        button.setContentAreaFilled(false);
        button.setBorder(BorderFactory.createEmptyBorder(0,0,0,0)); // Especially important
    }
    
    public void setBtn()// Xóa viền button add, back and search
    {
        setBtnNoBorder(btnAdd);
        setBtnNoBorder(btnSearch);
        setBtnNoBorder(btnBack);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        topicTable = new javax.swing.JTable();
        topicBox = new javax.swing.JComboBox<>();
        txtTopicSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JToggleButton();
        btnAdd = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        topicTable.setAutoCreateRowSorter(true);
        topicTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        topicTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "English", "Vietnames"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        topicTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(topicTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 210, 980, 380);

        topicBox.setBackground(new java.awt.Color(240, 240, 240));
        topicBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        topicBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicBoxActionPerformed(evt);
            }
        });
        getContentPane().add(topicBox);
        topicBox.setBounds(860, 130, 240, 60);

        txtTopicSearch.setBackground(new java.awt.Color(240, 240, 240));
        txtTopicSearch.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtTopicSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTopicSearchMouseClicked(evt);
            }
        });
        txtTopicSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTopicSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtTopicSearch);
        txtTopicSearch.setBounds(120, 130, 230, 60);

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(350, 130, 140, 60);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(10, 10, 110, 110);

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(540, 600, 150, 70);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TOPIC (1).png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1210, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topicBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicBoxActionPerformed
        //bắt sự kiện chọn combobox chủ đề
        model.setRowCount(0);
        showTable(topicBox.getSelectedItem().toString());
    }//GEN-LAST:event_topicBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Bắt sự kiện nút Back
        this.dispose();
        new HomeFrm();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       // Bắt sự kiên nút Search
        if (txtTopicSearch.getText().isEmpty()) {
            announcement("Please enter topic's name");
        } else {
            if (tp.checkTopicName(txtTopicSearch.getText())) {
                model.setRowCount(0);
                showTable(txtTopicSearch.getText());
            } else {
                announcement("No result");
                txtTopicSearch.setText("");
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtTopicSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTopicSearchMouseClicked
        txtTopicSearch.setText("");
    }//GEN-LAST:event_txtTopicSearchMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Bắt sự kiện nút add
        int[] indexs = topicTable.getSelectedRows();// vi tri cac dong word được chọn
        if (indexs.length == 0)
        {// Nếu chưa chọn
            announcement("Must have select at least a word");
        } else {
            
            int countSuccess = 0, countFalse = 0;
            for (int i = 0; i < indexs.length; i++)
            {
                String en = (String) topicTable.getValueAt(indexs[i], 0);
                if (new searchCtl().checkWordExits(topicCtl.idperson, en))
                {
                    countFalse++;
                } else 
                {
                    tp.addWordToPersonList(topicCtl.idperson, tp.getIDword(en));
                    countSuccess++;
                }
            }
            if (countSuccess == 0 && countFalse == 1)  // Mệt quá lười nghĩ thêm==> nghịch tí nên hơi nhiều trường hợp
            {
                announcement("The word is exits in your vocabulary");
            }
            else if (countSuccess == 0 && countFalse > 1) 
            {
                announcement("Add " + countFalse + " word failed");
            } 
            else if (countSuccess == 1 && countFalse == 0) 
            {
                announcement("Add a word sucessfully");
            }
            else if (countSuccess > 1 && countFalse == 0) 
            {
                announcement("Add " + countSuccess + " word sucessfully");
            } 
            else if (countSuccess == 1 && countFalse == 1)
            {
                announcement("Add a word sucessfully and a word failed");
            } else if (countSuccess == 1 && countFalse > 1)
            {
                announcement("Add a word sucessfully, " + countFalse + " words failed");
            } else if (countSuccess > 1 && countFalse == 1)
            {
                announcement("Add " + countSuccess + " words sucessfully, a word failed");
            } else
            {
                announcement("Add " + countSuccess + " words sucessfully, " + countFalse + " words failed");
            }
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void txtTopicSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTopicSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTopicSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopicFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopicFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopicFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopicFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopicFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAdd;
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> topicBox;
    private javax.swing.JTable topicTable;
    private javax.swing.JTextField txtTopicSearch;
    // End of variables declaration//GEN-END:variables

}
